# Add the contents of this file to `config.toml` to enable "fast build" configuration. Please read the notes below.

# NOTE: For maximum performance, build using a nightly compiler
# If you are using rust stable, remove the "-Zshare-generics=y" below.

[build]
rustflags = ["-Ctarget-cpu=native", "-Zthreads=0", "-Clink-arg=-fuse-ld=lld"]

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-Zshare-generics=y"]

[target.x86_64-apple-darwin]
linker = "clang"
rustflags = ["-Zshare-generics=y"]

[target.aarch64-apple-darwin]
linker = "clang"
rustflags = ["-Zshare-generics=y"]

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
rustflags = ["-Zshare-generics=n"]
